# version: 0.2

# phases:
#   install:
#     commands:
#       - echo Installing NGINX
#       - sudo apt-get update
#       - sudo apt-get install nginx -y

#   build:
#     commands:
#       - echo Build started on `date`
#       - cp index.html /var/www/html/

#   post_build:
#     commands:
#       - echo Configuring NGINX

# artifacts:
#   files:
#     - "**/*"
version: 0.2
phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - echo Creating ZIP file
      - zip -r build-output.zip ./* # Create a ZIP file of the directory

artifacts:
  files:
    - buildspec-output.zip # Specify the ZIP file as the artifact
  discard-paths: yes # Flatten directory structure
  base-directory: . # Base directory where the ZIP file is located
  name: buildspec-output.zip # Name of the ZIP file in S3 with folder path
  override-artifact-name: true # Ensure the artifact name is exactly as specified
